name: Push CI

on: [push]

env:
  APP_VERSION: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Get version
      uses: tyankatsu0105/read-package-version-actions@v1
      id: package-version

    - name: Configure git
      run: |
        git config user.name ${{ secrets.GIT_BOT_USERNAME }}
        git config user.email ${{ secrets.GIT_BOT_EMAIL }}
        git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/{{ secrets.GIT_REPO }}

    - name: Configure GH npm
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> ~/.npmrc
        echo "@nexcella:registry=https://npm.pkg.github.com" >> ~/.npmrc
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

    - name: npm install, build, and test
      run: |
        npm i
        npm i --only=dev
        npm test
        npm run build --if-present
      env:
        CI: true
        NODE_ENV: production
        APP_API_BASE_PATH: ${{ secrets.API_PATH }}

    - name: Version
      if: github.ref == 'refs/heads/master' && github.actor != 'nexcella-bot'
      run: npm run semantic-release
      env:
        CI: true

    - name: Docker login
      if: github.ref == 'refs/heads/master' && github.actor == 'nexcella-bot'
      run: echo ${{ secrets.GH_TOKEN }} | docker login docker.pkg.github.com -u nexcella-bot --password-stdin

    - name: Docker build
      if: github.ref == 'refs/heads/master' && github.actor == 'nexcella-bot'
      run: docker build -t docker.pkg.github.com/a-shabanov/comein-admin-frontend/app-package:${{ steps.package-version.outputs.version }}.$GITHUB_RUN_NUMBER .

    - name: Docker push
      if: github.ref == 'refs/heads/master' && github.actor == 'nexcella-bot'
      run: docker push docker.pkg.github.com/a-shabanov/comein-admin-frontend/app-package:${{ steps.package-version.outputs.version }}.$GITHUB_RUN_NUMBER
