name: App process

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
    - run: npm install
    - run: npm test
      env:
        CI: true
    - run: release
