name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Release
      run: npm run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CI: true
