name: Release

on:
  push:
    branches:
      - master
      - develop
      - release/*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Release
      run: npm run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CI: true
