name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    needs:
    steps:
    - name: Release
      run: npm run semantic-release
      needs: [test]
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CI: true
