name: Release

on:
  push:
    branches:
      - master
      - develop
      - release/**'

jobs:
  release:
    name: Release
    run: npm run semantic-release || true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      CI: true
